# **TP 02 :** Q-Learning

In [1]:
import gymnasium as gym
import numpy as np

##### **Exercise 1: Explore the FrozenLake environment from OpenAI Gym.**

##### Charger l’environnement FrozenLake-v1 de OpenAI Gym.

In [12]:
env = gym.make("FrozenLake-v1", is_slippery=False)


##### Afficher les informations de l'espace d'états et d'actions

In [13]:
print("Espace d'états:", env.observation_space.n)
print("Espace d'actions:", env.action_space.n)

Espace d'états: 16
Espace d'actions: 4


Exécuter une boucle avec des actions aléatoires

In [8]:
num_episodes = 40

env.reset()
for episode in range(num_episodes):
    state = env.reset()
    done = False
    total_reward = 0
    
    while not done:
        action = env.action_space.sample()  # Action aléatoire
        next_state, reward, done, info,_= env.step(action)
        total_reward += reward
        state = next_state
        print(f"Épisode {episode + 1},{action}, Récompense totale: {total_reward}")

Épisode 1,2, Récompense totale: 0.0
Épisode 1,3, Récompense totale: 0.0
Épisode 1,3, Récompense totale: 0.0
Épisode 1,1, Récompense totale: 0.0
Épisode 2,3, Récompense totale: 0.0
Épisode 2,1, Récompense totale: 0.0
Épisode 2,3, Récompense totale: 0.0
Épisode 2,2, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,3, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,1, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,1, Récompense totale: 0.0
Épisode 2,3, Récompense totale: 0.0
Épisode 2,1, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,3, Récompense totale: 0.0
Épisode 2,1, Récompense totale: 0.0
Épisode 2,2, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,2, Récompense totale: 0.0
Épisode 2,0, Récompense totale: 0.0
Épisode 2,3, Récompense totale: 0.0
Épisode 2,1, Récompense tota

##### **Exercice 2 : Implémentation de la méthode d'initialisation**     

Initialisation de la Q-Table


In [5]:
q_table = np.zeros((env.observation_space.n, env.action_space.n))


print("Q-Table initialisée :")
print(q_table)

Q-Table initialisée :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### **Exercice 3 : Implémentation du Q-Learning avec Mise à Jour**

Définir les hyperparamètres : taux d'apprentissage (alpha), facteur de discount (gamma), epsilon pour l'exploration

In [6]:
alpha = 0.1 
gamma = 0.99  
epsilon = 1.0  
epsilon_decay = 0.995  
num_episodes = 5000  

In [3]:
env = gym.make("FrozenLake-v1", is_slippery=False)
for episode in range(num_episodes):
    state,_ = env.reset()
    done = False
    
    while not done:
        
           
        if np.random.rand() < epsilon:
            action = env.action_space.sample() 
        else:
            action = np.argmax(q_table[state]) 
        
        next_state, reward, done, info, _ = env.step(action)
        q_table[state, action] = q_table[state, action] + alpha * (reward + gamma * np.max(q_table[next_state]) - q_table[state, action])
        
        state = next_state
    
   
    epsilon *= epsilon_decay

print("Q-Table après apprentissage :")
print(q_table)


Q-Table après apprentissage :
[[0.61315579 0.95099005 0.06499657 0.68175736]
 [0.34732827 0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.65171488 0.96059601 0.         0.57708892]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.54839729 0.         0.970299   0.67722417]
 [0.44634884 0.9801     0.35074514 0.        ]
 [0.         0.79069954 0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.54543722 0.99       0.5785136 ]
 [0.48645694 0.5151126  1.         0.25726121]
 [0.         0.         0.         0.        ]]


##### **Exercice 4 : Évaluation des Performances de l'Agent**

In [4]:

successes = 0

for _ in range(num_episodes):
    state,_ = env.reset()
    done = False
    
    while not done:
       
          
        action = np.argmax(q_table[state])  # Action optimale
        next_state, reward, done, info, _ = env.step(action)
        state = next_state
    
    if reward == 1:
        successes += 1

success_rate = successes / num_episodes
print(f"Taux de réussite : {success_rate * 100}%")

Taux de réussite : 100.0%
